service: service-name

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  profile: hsjang
  stage: prod
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any